### ISSUE TITLE
Environment variables needed

### ISSUE THREAD

**Issue by sylvain-combe-sonarsource** [ngrok/docker-ngrok#23]
Hello
One should not need to write some distinct YAML to configure a simple docker service.

That's why I like the wernight/ngrok image; it provides all the env variables I needed to configure an ngrok v2 directly from my compose stack config file.
As I need to move to ngrok v3, I'd like to get at least the same level of functionality from the official image.
The easisest path to do so would be to map each [global parameters](https://ngrok.com/docs/ngrok-agent/config#config-ngrok-global-options) to an environment variable.

Thanks!

**Comment by russorat** [comment]
Hi @sylvain-combe-sonarsource thanks for the issue. I agree this makes sense. I've opened up an internal issue to track this. 

We'd also be very happy to review a PR for something like this. If you want to chat about possible solutions, you can join us in ngrok.com/slack

**Comment by MrAdam** [comment]
It's still possible to configure it directly from the docker-compose file, by supplying a `command` argument, which gets appended to the entrypoint script, and passed onwards to `ngrok`
``` yaml
services:
  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN
    command: http https://host.docker.internal:8080 --log stdout
```
